import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { expect, test } from "vitest";
import { removeStaleGeneratedFiles } from "./cleanup.ts";

const MARKER_LINE = "// Generated by prisma-factorio. Do not edit.\n";

async function survivesCleanup(params: { fileName: string; content: string; keep: string[] }): Promise<boolean> {
  const dir = mkdtempSync(join(tmpdir(), "prisma-factorio-"));
  try {
    const filePath = join(dir, params.fileName);
    writeFileSync(filePath, params.content);
    await removeStaleGeneratedFiles({ outputDir: dir, keep: params.keep });
    return existsSync(filePath);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

test("a marker-bearing file absent from the keep set is deleted", async () => {
  const survived = await survivesCleanup({
    fileName: "RemovedModel.ts",
    content: `${MARKER_LINE}export abstract class RemovedModelFactoryBase {}\n`,
    keep: ["User.ts", "index.ts"],
  });

  expect(survived).toBe(false);
});

test("a marker-less file in the output directory survives", async () => {
  const survived = await survivesCleanup({
    fileName: "notes.ts",
    content: "export const handWritten = true;\n",
    keep: ["index.ts"],
  });

  expect(survived).toBe(true);
});

test("a marker-bearing file in the keep set is not deleted", async () => {
  const survived = await survivesCleanup({
    fileName: "User.ts",
    content: `${MARKER_LINE}export abstract class UserFactoryBase {}\n`,
    keep: ["User.ts"],
  });

  expect(survived).toBe(true);
});

test("a file merely mentioning the marker after its first line survives", async () => {
  const survived = await survivesCleanup({
    fileName: "copied-snippet.ts",
    content: `export const handWritten = true;\n${MARKER_LINE}`,
    keep: ["index.ts"],
  });

  expect(survived).toBe(true);
});

test("a subdirectory in the output directory survives", async () => {
  const dir = mkdtempSync(join(tmpdir(), "prisma-factorio-"));
  try {
    const subdir = join(dir, "user-owned");
    mkdirSync(subdir);

    await removeStaleGeneratedFiles({ outputDir: dir, keep: ["index.ts"] });

    expect(existsSync(subdir)).toBe(true);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("a missing output directory is a no-op", async () => {
  const dir = mkdtempSync(join(tmpdir(), "prisma-factorio-"));
  try {
    const missing = join(dir, "never-generated");

    await expect(removeStaleGeneratedFiles({ outputDir: missing, keep: [] })).resolves.toBeUndefined();
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
