import { expect, test } from "vitest";
import { datamodelFixture, modelFixture } from "../tests/dmmf.ts";
import { emitFactoryFiles, emitModelFactoryFile } from "./emit.ts";

test("a model emits a file named after the model", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "User" }));

  expect(file.path).toBe("User.ts");
});

test("the emitted file exports the factory base class of the model", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "Post" }));

  expect(file.content).toContain("export class PostFactoryBase {}");
});

test("a datamodel emits one factory base file per model", () => {
  const datamodel = datamodelFixture([modelFixture({ name: "User" }), modelFixture({ name: "Post" })]);

  const files = emitFactoryFiles(datamodel);

  expect(files.map((file) => file.path)).toEqual(["User.ts", "Post.ts"]);
});

test("the emitted file starts with a generated-file header comment", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "User" }));

  expect(file.content).toMatch(/^\/\/ Generated by prisma-factorio\./);
});
