import { expect, test } from "vitest";
import { datamodelFixture, generatorConfigFixture, modelFixture } from "../tests/dmmf.ts";
import {
  emitBarrelFile,
  emitFactoryFiles,
  emitModelFactoryFile,
  GENERATED_FILE_MARKER,
  resolveClientImportDir,
} from "./emit.ts";

test("a model emits a file named after the model", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "User" }), "../client");

  expect(file.path).toBe("User.ts");
});

test("the emitted base class is abstract and pins the Factory generics to the model CreateInput and Model", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "Post" }), "../client");

  expect(file.content).toContain("export abstract class PostFactoryBase extends Factory<PostCreateInput, PostModel> {");
});

test("the emitted base class bakes the model's Prisma delegate name", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "Post" }), "../client");

  expect(file.content).toContain('protected readonly prismaDelegate = "post";');
});

test("the baked delegate name lowercases only the first letter of a multi-word model name", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "UserProfile" }), "../client");

  expect(file.content).toContain('protected readonly prismaDelegate = "userProfile";');
});

// "aPIKey" must match Prisma's own lowerFirst delegate mapping (model APIKey
// -> prisma.aPIKey), however wrong it looks; a "nicer" apiKey would typecheck
// fine and miss the delegate at runtime.
test("an acronym-led model name bakes Prisma's lowerFirst delegate name verbatim", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "APIKey" }), "../client");

  expect(file.content).toContain('protected readonly prismaDelegate = "aPIKey";');
});

test("the emitted file imports Factory from the prisma-factorio runtime", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "User" }), "../client");

  expect(file.content).toContain('import { Factory } from "prisma-factorio/factories";');
});

test("the emitted file imports the model CreateInput and Model types from the client models barrel", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "User" }), "../../custom/client");

  expect(file.content).toContain('import type { UserCreateInput, UserModel } from "../../custom/client/models.ts";');
});

test("a datamodel emits one factory base file per model plus a barrel index", () => {
  const datamodel = datamodelFixture([modelFixture({ name: "User" }), modelFixture({ name: "Post" })]);

  const files = emitFactoryFiles({
    datamodel,
    outputDir: "/app/generated/prisma-factorio",
    otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: "/app/custom/client" })],
  });

  expect(files.map((file) => file.path)).toEqual(["User.ts", "Post.ts", "index.ts"]);
  expect(files[0]?.content).toContain('from "../../custom/client/models.ts"');
  expect(files[2]?.content).toContain('import type { PrismaClient } from "../../custom/client/client.ts";');
});

test("the barrel re-exports every model factory base from its model file", () => {
  const file = emitBarrelFile([modelFixture({ name: "User" }), modelFixture({ name: "Post" })], "../client");

  expect(file.path).toBe("index.ts");
  expect(file.content).toContain('export { UserFactoryBase } from "./User.ts";');
  expect(file.content).toContain('export { PostFactoryBase } from "./Post.ts";');
});

test("the barrel emits a typed initPrismaFactorio wrapper bound to the schema's PrismaClient", () => {
  const file = emitBarrelFile([modelFixture({ name: "User" })], "../../custom/client");

  expect(file.content).toContain('import type { PrismaClient } from "../../custom/client/client.ts";');
  expect(file.content).toContain(
    'import { initPrismaFactorio as initPrismaFactorioRuntime } from "prisma-factorio/factories";',
  );
  expect(file.content).toContain(
    "export function initPrismaFactorio(options: { prisma: PrismaClient | (() => PrismaClient) }): void {",
  );
  expect(file.content).toContain("initPrismaFactorioRuntime(options);");
});

test("the barrel starts with a generated-file header comment", () => {
  const file = emitBarrelFile([modelFixture({ name: "User" })], "../client");

  expect(file.content).toMatch(/^\/\/ Generated by prisma-factorio\./);
});

test("the emitted file starts with a generated-file header comment", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "User" }), "../client");

  expect(file.content).toMatch(/^\/\/ Generated by prisma-factorio\./);
});

test("every emitted file starts with the shared generated-file marker", () => {
  const modelFile = emitModelFactoryFile(modelFixture({ name: "User" }), "../client");
  const barrelFile = emitBarrelFile([modelFixture({ name: "User" })], "../client");

  expect(modelFile.content.startsWith(`${GENERATED_FILE_MARKER}\n`)).toBe(true);
  expect(barrelFile.content.startsWith(`${GENERATED_FILE_MARKER}\n`)).toBe(true);
});

test("a single prisma-client generator resolves to a relative dir from the factory output dir", () => {
  const dir = resolveClientImportDir({
    outputDir: "/app/generated/prisma-factorio",
    otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/client" })],
  });

  expect(dir).toBe("../client");
});

test("a client dir nested under the factory output dir resolves with a ./ prefix", () => {
  const dir = resolveClientImportDir({
    outputDir: "/app/generated",
    otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/client" })],
  });

  expect(dir).toBe("./client");
});

test("clientOutput overrides otherGenerators detection", () => {
  const dir = resolveClientImportDir({
    outputDir: "/app/generated/prisma-factorio",
    otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/client" })],
    clientOutput: "/app/custom/client",
  });

  expect(dir).toBe("../../custom/client");
});

test("a factory output dir equal to the clientOutput dir fails naming both directories", () => {
  const resolve = () =>
    resolveClientImportDir({
      outputDir: "/app/generated/shared",
      otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/client" })],
      clientOutput: "/app/generated/shared",
    });

  expect(resolve).toThrow(/\/app\/generated\/shared.*\/app\/generated\/shared/);
  expect(resolve).toThrow(/`output` must differ from the client output/);
});

test("a factory output dir equal to the detected prisma-client output dir fails naming both directories", () => {
  const resolve = () =>
    resolveClientImportDir({
      outputDir: "/app/generated/client",
      otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/client" })],
    });

  expect(resolve).toThrow(/\/app\/generated\/client.*\/app\/generated\/client/);
  expect(resolve).toThrow(/`output` must differ from the client output/);
});

test("zero prisma-client generators without clientOutput fails naming the clientOutput option", () => {
  const resolve = () =>
    resolveClientImportDir({
      outputDir: "/app/generated/prisma-factorio",
      otherGenerators: [generatorConfigFixture({ provider: "prisma-client-py", output: "/app/generated/client" })],
    });

  expect(resolve).toThrow(/no generator with provider "prisma-client"/);
  expect(resolve).toThrow(/clientOutput/);
});

test("multiple prisma-client generators without clientOutput fails naming the clientOutput option", () => {
  const resolve = () =>
    resolveClientImportDir({
      outputDir: "/app/generated/prisma-factorio",
      otherGenerators: [
        generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/client" }),
        generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/other-client" }),
      ],
    });

  expect(resolve).toThrow(/2 generators with provider "prisma-client"/);
  expect(resolve).toThrow(/clientOutput/);
});

test("a matched prisma-client generator without a resolved output fails naming the clientOutput option", () => {
  const resolve = () =>
    resolveClientImportDir({
      outputDir: "/app/generated/prisma-factorio",
      otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: null })],
    });

  expect(resolve).toThrow(/clientOutput/);
});
