import { expect, test } from "vitest";
import { datamodelFixture, generatorConfigFixture, modelFixture } from "../tests/dmmf.ts";
import { emitBarrelFile, emitFactoryFiles, emitModelFactoryFile, resolveClientImportDir } from "./emit.ts";

test("a model emits a file named after the model", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "User" }), "../client");

  expect(file.path).toBe("User.ts");
});

test("the emitted base class is abstract and pins the Factory generic to the model CreateInput", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "Post" }), "../client");

  expect(file.content).toContain("export abstract class PostFactoryBase extends Factory<PostCreateInput> {}");
});

test("the emitted file imports Factory from the prisma-factorio runtime", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "User" }), "../client");

  expect(file.content).toContain('import { Factory } from "prisma-factorio/factories";');
});

test("the emitted file imports the model CreateInput type from the client models barrel", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "User" }), "../../custom/client");

  expect(file.content).toContain('import type { UserCreateInput } from "../../custom/client/models.ts";');
});

test("a datamodel emits one factory base file per model plus a barrel index", () => {
  const datamodel = datamodelFixture([modelFixture({ name: "User" }), modelFixture({ name: "Post" })]);

  const files = emitFactoryFiles({
    datamodel,
    outputDir: "/app/generated/prisma-factorio",
    otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/client" })],
  });

  expect(files.map((file) => file.path)).toEqual(["User.ts", "Post.ts", "index.ts"]);
  expect(files[0]?.content).toContain('from "../client/models.ts"');
});

test("the barrel re-exports every model factory base from its model file", () => {
  const file = emitBarrelFile([modelFixture({ name: "User" }), modelFixture({ name: "Post" })]);

  expect(file.path).toBe("index.ts");
  expect(file.content).toContain('export { UserFactoryBase } from "./User.ts";');
  expect(file.content).toContain('export { PostFactoryBase } from "./Post.ts";');
});

test("the barrel starts with a generated-file header comment", () => {
  const file = emitBarrelFile([modelFixture({ name: "User" })]);

  expect(file.content).toMatch(/^\/\/ Generated by prisma-factorio\./);
});

test("the emitted file starts with a generated-file header comment", () => {
  const file = emitModelFactoryFile(modelFixture({ name: "User" }), "../client");

  expect(file.content).toMatch(/^\/\/ Generated by prisma-factorio\./);
});

test("a single prisma-client generator resolves to a relative dir from the factory output dir", () => {
  const dir = resolveClientImportDir({
    outputDir: "/app/generated/prisma-factorio",
    otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/client" })],
  });

  expect(dir).toBe("../client");
});

test("a client dir nested under the factory output dir resolves with a ./ prefix", () => {
  const dir = resolveClientImportDir({
    outputDir: "/app/generated",
    otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/client" })],
  });

  expect(dir).toBe("./client");
});

test("clientOutput overrides otherGenerators detection", () => {
  const dir = resolveClientImportDir({
    outputDir: "/app/generated/prisma-factorio",
    otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/client" })],
    clientOutput: "/app/custom/client",
  });

  expect(dir).toBe("../../custom/client");
});

test("zero prisma-client generators without clientOutput fails naming the clientOutput option", () => {
  const resolve = () =>
    resolveClientImportDir({
      outputDir: "/app/generated/prisma-factorio",
      otherGenerators: [generatorConfigFixture({ provider: "prisma-client-py", output: "/app/generated/client" })],
    });

  expect(resolve).toThrow(/no generator with provider "prisma-client"/);
  expect(resolve).toThrow(/clientOutput/);
});

test("multiple prisma-client generators without clientOutput fails naming the clientOutput option", () => {
  const resolve = () =>
    resolveClientImportDir({
      outputDir: "/app/generated/prisma-factorio",
      otherGenerators: [
        generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/client" }),
        generatorConfigFixture({ provider: "prisma-client", output: "/app/generated/other-client" }),
      ],
    });

  expect(resolve).toThrow(/2 generators with provider "prisma-client"/);
  expect(resolve).toThrow(/clientOutput/);
});

test("a matched prisma-client generator without a resolved output fails naming the clientOutput option", () => {
  const resolve = () =>
    resolveClientImportDir({
      outputDir: "/app/generated/prisma-factorio",
      otherGenerators: [generatorConfigFixture({ provider: "prisma-client", output: null })],
    });

  expect(resolve).toThrow(/clientOutput/);
});
