import { relative, resolve, sep } from "node:path";
import type { DMMF, GeneratorConfig } from "@prisma/generator-helper";

const CLIENT_PROVIDER = "prisma-client";

/**
 * First line of every file this generator emits. Stale-file cleanup deletes
 * only files starting with this marker, so it must open every generated file
 * verbatim.
 *
 * @example
 * emitBarrelFile([], "../client").content.startsWith(GENERATED_FILE_MARKER); // true
 */
export const GENERATED_FILE_MARKER = "// Generated by prisma-factorio. Do not edit.";

const CLIENT_OUTPUT_HINT =
  "Set the `clientOutput` option on the prismaFactorio generator to the Prisma client output directory.";

/**
 * A file produced by the generator; `path` is relative to the generator
 * output directory.
 *
 * @example
 * const file: GeneratedFile = { path: "User.ts", content: "export class UserFactoryBase {}" };
 */
export interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Resolves the directory the generated factories import client types from, as
 * a relative import specifier from the factory output directory. The client
 * directory is `clientOutput` when given, otherwise the output of the single
 * `prisma-client` generator in `otherGenerators`. Fails when the factory
 * output directory equals the client directory, since the factories would
 * overwrite the client files.
 *
 * @example
 * resolveClientImportDir({
 *   outputDir: "/app/generated/prisma-factorio",
 *   otherGenerators: [clientGeneratorConfig],
 * }); // "../client"
 */
export function resolveClientImportDir(params: {
  outputDir: string;
  otherGenerators: readonly GeneratorConfig[];
  clientOutput?: string;
}): string {
  const clientDir = params.clientOutput ?? detectClientOutputDir(params.otherGenerators);
  if (resolve(params.outputDir) === resolve(clientDir)) {
    throw new Error(
      `prisma-factorio: the factory output directory "${params.outputDir}" is the same as the Prisma client output directory "${clientDir}"; the factory \`output\` must differ from the client output.`,
    );
  }
  const relativeDir = relative(params.outputDir, clientDir).split(sep).join("/");
  return relativeDir.startsWith(".") ? relativeDir : `./${relativeDir}`;
}

function detectClientOutputDir(otherGenerators: readonly GeneratorConfig[]): string {
  const clients = otherGenerators.filter((generator) => generator.provider.value === CLIENT_PROVIDER);
  if (clients.length === 0) {
    throw new Error(
      `prisma-factorio: no generator with provider "${CLIENT_PROVIDER}" was found in the schema, so the Prisma client types cannot be located. ${CLIENT_OUTPUT_HINT}`,
    );
  }
  if (clients.length > 1) {
    throw new Error(
      `prisma-factorio: found ${String(clients.length)} generators with provider "${CLIENT_PROVIDER}", so the Prisma client types cannot be located unambiguously. ${CLIENT_OUTPUT_HINT}`,
    );
  }
  const output = clients[0]?.output?.value;
  if (output === undefined || output === null) {
    throw new Error(
      `prisma-factorio: the "${CLIENT_PROVIDER}" generator resolved no output directory. ${CLIENT_OUTPUT_HINT}`,
    );
  }
  return output;
}

/**
 * Emits the factory base class file for one model; `clientImportDir` is the
 * relative import specifier of the Prisma client directory as resolved by
 * {@link resolveClientImportDir}.
 *
 * @example
 * emitModelFactoryFile(model, "../client").path; // "User.ts" for a model named User
 */
export function emitModelFactoryFile(model: DMMF.Model, clientImportDir: string): GeneratedFile {
  const createInput = `${model.name}CreateInput`;
  const modelType = `${model.name}Model`;
  const relations = model.fields.filter((field) => field.kind === "object");
  const content =
    relations.length === 0
      ? emitPlainBase(model, createInput, modelType, clientImportDir)
      : emitRelationalBase(model, relations, createInput, modelType, clientImportDir);
  return { path: `${model.name}.ts`, content };
}

function emitPlainBase(model: DMMF.Model, createInput: string, modelType: string, clientImportDir: string): string {
  return `${GENERATED_FILE_MARKER}
import { Factory } from "prisma-factorio/factories";
import type { ${createInput}, ${modelType} } from "${clientImportDir}/models.ts";

export abstract class ${model.name}FactoryBase extends Factory<${createInput}, ${modelType}> {
  protected readonly prismaDelegate = "${delegateName(model.name)}";
}
`;
}

// A relational base pins a third Factory generic: a homomorphic mapped type
// over the CreateInput that widens each relation field to also accept a
// FactoryValue of the related model's factory, preserving the field's
// optionality so a to-many relation stays optional in the definition.
function emitRelationalBase(
  model: DMMF.Model,
  relations: readonly DMMF.Field[],
  createInput: string,
  modelType: string,
  clientImportDir: string,
): string {
  const relationImports = relatedFactoryImports(model, relations);
  const definition = `${model.name}FactoryDefinition`;
  const relationMap = `${model.name}RelationFactories`;
  const mapEntries = relations.map((field) => `  ${field.name}: FactoryValue<${field.type}FactoryBase>;`).join("\n");
  return `${GENERATED_FILE_MARKER}
import { Factory, type FactoryValue } from "prisma-factorio/factories";
import type { ${createInput}, ${modelType} } from "${clientImportDir}/models.ts";
${relationImports}
type ${relationMap} = {
${mapEntries}
};

type ${definition} = {
  [K in keyof ${createInput}]: K extends keyof ${relationMap}
    ? ${createInput}[K] | ${relationMap}[K]
    : ${createInput}[K];
};

export abstract class ${model.name}FactoryBase extends Factory<
  ${createInput},
  ${modelType},
  ${definition}
> {
  protected readonly prismaDelegate = "${delegateName(model.name)}";
}
`;
}

// Type-only imports of the related factory bases, one per distinct related
// model in first-appearance order. The model's own base is skipped: a
// self-relation references a class declared in this same file.
function relatedFactoryImports(model: DMMF.Model, relations: readonly DMMF.Field[]): string {
  const relatedModels = [...new Set(relations.map((field) => field.type))].filter((name) => name !== model.name);
  return relatedModels.map((name) => `import type { ${name}FactoryBase } from "./${name}.ts";\n`).join("");
}

// The Prisma client exposes each model as a delegate property named with the
// model name's first letter lowercased (model User -> prisma.user).
function delegateName(modelName: string): string {
  return modelName.charAt(0).toLowerCase() + modelName.slice(1);
}

/**
 * Emits the barrel index re-exporting every model factory base plus a typed
 * `initPrismaFactorio` wrapper pinned to the schema's `PrismaClient`, so users
 * can import everything from the output directory's `index.ts`;
 * `clientImportDir` is the relative import specifier of the Prisma client
 * directory as resolved by {@link resolveClientImportDir}.
 *
 * @example
 * emitBarrelFile([userModel], "../client").content;
 * // includes `export { UserFactoryBase } from "./User.ts";`
 */
export function emitBarrelFile(models: readonly DMMF.Model[], clientImportDir: string): GeneratedFile {
  const exports = models.map((model) => `export { ${model.name}FactoryBase } from "./${model.name}.ts";`);
  const content = `${GENERATED_FILE_MARKER}
import { initPrismaFactorio as initPrismaFactorioRuntime } from "prisma-factorio/factories";
import type { PrismaClient } from "${clientImportDir}/client.ts";

${exports.join("\n")}

/**
 * Registers the Prisma client that factory \`create()\` calls persist through,
 * typed to the client generated for this schema.
 *
 * @example
 * initPrismaFactorio({ prisma: new PrismaClient({ adapter }) });
 */
export function initPrismaFactorio(options: { prisma: PrismaClient | (() => PrismaClient) }): void {
  initPrismaFactorioRuntime(options);
}
`;
  return { path: "index.ts", content };
}

/**
 * Emits every factory base class file for the given datamodel, one per model,
 * plus the barrel index.
 *
 * @example
 * emitFactoryFiles({
 *   datamodel: options.dmmf.datamodel,
 *   outputDir: "/app/generated/prisma-factorio",
 *   otherGenerators: options.otherGenerators,
 * }).map((file) => file.path); // ["User.ts", "Post.ts", "index.ts"]
 */
export function emitFactoryFiles(params: {
  datamodel: DMMF.Datamodel;
  outputDir: string;
  otherGenerators: readonly GeneratorConfig[];
  clientOutput?: string;
}): GeneratedFile[] {
  const clientImportDir = resolveClientImportDir(params);
  const modelFiles = params.datamodel.models.map((model) => emitModelFactoryFile(model, clientImportDir));
  return [...modelFiles, emitBarrelFile(params.datamodel.models, clientImportDir)];
}
