import { relative, resolve, sep } from "node:path";
import type { DMMF, GeneratorConfig } from "@prisma/generator-helper";

const CLIENT_PROVIDER = "prisma-client";

/**
 * First line of every file this generator emits. Stale-file cleanup deletes
 * only files starting with this marker, so it must open every generated file
 * verbatim.
 *
 * @example
 * emitBarrelFile([]).content.startsWith(GENERATED_FILE_MARKER); // true
 */
export const GENERATED_FILE_MARKER = "// Generated by prisma-factorio. Do not edit.";

const CLIENT_OUTPUT_HINT =
  "Set the `clientOutput` option on the prismaFactorio generator to the Prisma client output directory.";

/**
 * A file produced by the generator; `path` is relative to the generator
 * output directory.
 *
 * @example
 * const file: GeneratedFile = { path: "User.ts", content: "export class UserFactoryBase {}" };
 */
export interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Resolves the directory the generated factories import client types from, as
 * a relative import specifier from the factory output directory. The client
 * directory is `clientOutput` when given, otherwise the output of the single
 * `prisma-client` generator in `otherGenerators`. Fails when the factory
 * output directory equals the client directory, since the factories would
 * overwrite the client files.
 *
 * @example
 * resolveClientImportDir({
 *   outputDir: "/app/generated/prisma-factorio",
 *   otherGenerators: [clientGeneratorConfig],
 * }); // "../client"
 */
export function resolveClientImportDir(params: {
  outputDir: string;
  otherGenerators: readonly GeneratorConfig[];
  clientOutput?: string;
}): string {
  const clientDir = params.clientOutput ?? detectClientOutputDir(params.otherGenerators);
  if (resolve(params.outputDir) === resolve(clientDir)) {
    throw new Error(
      `prisma-factorio: the factory output directory "${params.outputDir}" is the same as the Prisma client output directory "${clientDir}"; the factory \`output\` must differ from the client output.`,
    );
  }
  const relativeDir = relative(params.outputDir, clientDir).split(sep).join("/");
  return relativeDir.startsWith(".") ? relativeDir : `./${relativeDir}`;
}

function detectClientOutputDir(otherGenerators: readonly GeneratorConfig[]): string {
  const clients = otherGenerators.filter((generator) => generator.provider.value === CLIENT_PROVIDER);
  if (clients.length === 0) {
    throw new Error(
      `prisma-factorio: no generator with provider "${CLIENT_PROVIDER}" was found in the schema, so the Prisma client types cannot be located. ${CLIENT_OUTPUT_HINT}`,
    );
  }
  if (clients.length > 1) {
    throw new Error(
      `prisma-factorio: found ${String(clients.length)} generators with provider "${CLIENT_PROVIDER}", so the Prisma client types cannot be located unambiguously. ${CLIENT_OUTPUT_HINT}`,
    );
  }
  const output = clients[0]?.output?.value;
  if (output === undefined || output === null) {
    throw new Error(
      `prisma-factorio: the "${CLIENT_PROVIDER}" generator resolved no output directory. ${CLIENT_OUTPUT_HINT}`,
    );
  }
  return output;
}

/**
 * Emits the factory base class file for one model; `clientImportDir` is the
 * relative import specifier of the Prisma client directory as resolved by
 * {@link resolveClientImportDir}.
 *
 * @example
 * emitModelFactoryFile(model, "../client").path; // "User.ts" for a model named User
 */
export function emitModelFactoryFile(model: DMMF.Model, clientImportDir: string): GeneratedFile {
  const createInput = `${model.name}CreateInput`;
  const content = `${GENERATED_FILE_MARKER}
import { Factory } from "prisma-factorio/factories";
import type { ${createInput} } from "${clientImportDir}/models.ts";

export abstract class ${model.name}FactoryBase extends Factory<${createInput}> {}
`;
  return { path: `${model.name}.ts`, content };
}

/**
 * Emits the barrel index re-exporting every model factory base, so users can
 * import all bases from the output directory's `index.ts`.
 *
 * @example
 * emitBarrelFile([userModel]).content;
 * // includes `export { UserFactoryBase } from "./User.ts";`
 */
export function emitBarrelFile(models: readonly DMMF.Model[]): GeneratedFile {
  const exports = models.map((model) => `export { ${model.name}FactoryBase } from "./${model.name}.ts";`);
  const content = `${GENERATED_FILE_MARKER}
${exports.join("\n")}
`;
  return { path: "index.ts", content };
}

/**
 * Emits every factory base class file for the given datamodel, one per model,
 * plus the barrel index.
 *
 * @example
 * emitFactoryFiles({
 *   datamodel: options.dmmf.datamodel,
 *   outputDir: "/app/generated/prisma-factorio",
 *   otherGenerators: options.otherGenerators,
 * }).map((file) => file.path); // ["User.ts", "Post.ts", "index.ts"]
 */
export function emitFactoryFiles(params: {
  datamodel: DMMF.Datamodel;
  outputDir: string;
  otherGenerators: readonly GeneratorConfig[];
  clientOutput?: string;
}): GeneratedFile[] {
  const clientImportDir = resolveClientImportDir(params);
  const modelFiles = params.datamodel.models.map((model) => emitModelFactoryFile(model, clientImportDir));
  return [...modelFiles, emitBarrelFile(params.datamodel.models)];
}
